<?php

// @codingStandardsIgnoreFile

/** @var \M2E\Otto\Block\Adminhtml\Widget\Info $block */
?>

<style type="text/css">

    div.Otto-widget-info {
        background: none repeat scroll 0 0 #FAFAFA !important;
        border: 1px solid #D6D6D6 !important;
        margin-bottom: 15px !important;
        padding: 10px 15px !important;
    }

    div.Otto-widget-info label {
        width: 100%;
        white-space: nowrap;
        text-overflow: ellipsis;
        overflow: hidden;
        display: inline-block;
    }

    div.Otto-widget-info span.label {
        font-weight: bold;
    }

    div.Otto-widget-info span.value {
        color: #8e9393;
    }

    div.Otto-widget-info ul {
        text-align: justify;
        line-height: 0;
        font-size: 1px;
    }

    div.Otto-widget-info ul:after {
        width: 100%;
        height: 0;
        visibility: hidden;
        overflow: hidden;
        content: '';
        display: inline-block;
    }

    div.Otto-widget-info ul li {
        display: inline-block;
        text-align: left;
        line-height: normal;
        font-size: 12px;
        vertical-align: top;
        max-width: 45%;
    }

    <?php foreach ($this->getInfo() as $index => $data) :?>
    #
    <?php /* @noEscape */ echo $this->getId() ?>
    ul li:nth-child(<?php /* @noEscape */ echo $index + 1; ?>) {
        width: <?php /* @noEscape */ echo $this->getInfoPartWidth($index); ?>;
        text-align: <?php /* @noEscape */ echo $this->getInfoPartAlign($index); ?>;
    }

    <?php endforeach; ?>

</style>

<div id="<?= /* @noEscape */ $this->getId() ?>" class="Otto-widget-info">
    <ul>
        <?php
        foreach ($block->getInfo() as $index => $data) : ?>
            <li>
                <label>
                <span class="label">
                    <?= /* @noEscape */ $data['label']; ?>:&nbsp;
                </span>
                    <span class="value">
                    <?= /* @noEscape */ $data['value']; ?>
                </span>
                </label>
            </li>
        <?php
        endforeach; ?>
    </ul>
</div>
