<?php

// @codingStandardsIgnoreFile

/** @var \M2E\Otto\Block\Adminhtml\General $block */

?>

<script type="text/javascript">

    <?php if ($block->getIsAjax()) : ?>
    BlockNoticeObj.init(true);

    <?php echo
        $block->jsPhp->render()
        . $block->jsTranslator->render()
        . $block->jsUrl->render()
        . $block->js->render();
    ?>

    initializationCustomAttributeInputs();
    initCollapsable();

    <?php else : ?>
    var BLOCK_NOTICES_SHOW = <?php echo $block->blockNoticesShow ? 'true' : 'false'; ?>;

    var IS_VIEW_OTTO = <?php echo json_encode($block->viewHelper->isCurrentViewOtto()); ?>;
    var IS_VIEW_CONFIGURATION = <?php echo json_encode($block->viewHelper->isCurrentViewConfiguration()); ?>;

    var Otto = {};

    require(['Otto/Otto', 'Otto/Plugin/Magento/AttributeCreator'], function (_Otto) {
        Otto = _Otto;

        // backward compatibility
        Otto.text = {};
        Otto.formData = {};
        Otto.customData = {};

        <?php echo $block->jsPhp->render(); ?>
        <?php echo $block->jsTranslator->render(); ?>
        <?php echo $block->jsUrl->render(); ?>

        window.CommonObj = new window.Common();
        CommonObj.initCommonValidators();

        window.BlockNoticeObj = new BlockNotice();
        BlockNoticeObj.init();

        <?php echo $block->js->render(); ?>

        window.initializationCustomAttributeInputs = function () {
            $$('select.Otto-custom-attribute-can-be-created').each(function (selectObj) {

                var handlerObj = new AttributeCreator(selectObj.id);
                handlerObj.setSelectObj(selectObj);

                if (handlerObj.alreadyHaveAddedOption()) {
                    return true;
                }

                handlerObj.injectAddOption();
            });
        };

        initializationCustomAttributeInputs();
        initCollapsable();
    });

    require(['Otto/ControlPanel'], function (controlPanel) {

        window.ControlPanelObj = new ControlPanel();
        window.ControlPanelObj.setControlPanelUrl('<?php echo $block->getUrl('*/controlPanel'); ?>')
    });

    <?php endif; ?>

</script>

<style type="text/css">
    <?php echo $block->css->render(); ?>
</style>
